#: import LedButton dro.components.toolbars.led_button

<StatusBar>:
  size_hint: 1, None
  height: 32
  orientation: "horizontal"

  LedButton:
    label: "COM"
    checkbox_value: app.board.connected or app.board.blink

  LedButton:
    label: "{:0.0f} Hz".format(root.comm_rate)

  LedButton:
    label: "{:0.0f}".format(root.fps)

  LedButton:
    label: "{:0.0f}".format(root.cycles)

  LedButton:
    label: app.version
